name: clean_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # The dependencies added are latest versions and different from tutorial video, so wish me luck
  # Service Locator
  get_it: ^5.0.0
  # Bloc for state management
  flutter_bloc: ^6.0.5
  # Value equality
  equatable: ^1.2.5
  # Functional Programming
  dartz: ^0.9.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.2
  # Local cache
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.2

flutter:
  uses-material-design: true
